name: admin_facile
description: AdminFacile, assistant administratif personnel.
publish_to: "none"
version: 20.4.28+113

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  image_picker: ^1.2.3
  google_mlkit_text_recognition: ^0.16.0
  shared_preferences: ^2.5.5
  file_picker: 10.3.10
  speech_to_text: ^7.4.0
  google_mlkit_translation: ^0.14.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  printing: ^5.14.2
  share_plus: ^11.1.0
  url_launcher: ^6.3.2
  http: ^1.6.0
  image: ^4.8.0
  supabase_flutter: ^2.16.0
  google_sign_in: ^7.2.0
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  default-flavor: france
  generate: true
  uses-material-design: true
  assets:
    - assets/branding/admin_facile_icon.png
    - assets/branding/admin_facile_logo.png
    - assets/adminfacile_logo.png
    - assets/adminfacile_mark.png
    - assets/google_g_logo.png
    - assets/images/hero_plume_document.jpg
    - assets/letters/library.json
    - assets/fonts/Roboto-Regular.ttf
    - assets/fonts/Roboto-Bold.ttf
